user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.index:
    resource: "@AppBundle/Controller/IndexController.php"
    type: annotation

app.post:
    resource: "@AppBundle/Controller/PostController.php"
    type: annotation
    prefix: /lista
app.comment:
    resource: "@AppBundle/Controller/CommentController.php"
    type: annotation
    prefix: /comment