user:
    resource: "@UserBundle/Resources/config/routing.yml"


app.post:
    resource: "@AppBundle/Controller/PostController.php"
    type: annotation
    prefix: /
app.comment:
    resource: "@AppBundle/Controller/CommentController.php"
    type: annotation
    prefix: /comment